use_frameworks!

target 'SI1-RatingView_Example' do
  pod 'SI1-RatingView', :path => 'https://github.com/SI-Du/SI1-RatingView.git'

  target 'SI1-RatingView_Tests' do
    inherit! :search_paths

    
  end
end
